apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: near-mainnet
spec:
  jobName: near
  module: default
  prober:
    url: near-exporter.guardian.svc.cluster.local
    path: /probe
  targets:
    staticConfig:
      static:
        - vsl-submitter.near
      relabelingConfigs:
        - replacement: "https://rpc.mainnet.near.org"
          targetLabel: __param_target

        - sourceLabels: [__address__]
          replacement: "$1"
          targetLabel: __param_account_id
